export const ContentList = [
  {
    id: 1,
    author: "Max Leiter",
    avatar: "https://github.com/maxleiter.png",
    fallback: "ML",
    views: 1234,
    likes: 123,
  },
  {
    id: 2,
    author: "Evil Rabbit",
    avatar: "https://github.com/evilrabbit.png",
    fallback: "ER",
    views: 5678,
    likes: 456,
  },
  {
    id: 3,
    author: "Shadcn",
    avatar: "https://github.com/shadcn.png",
    fallback: "SH",
    views: 9012,
    likes: 789,
  },
  {
    id: 4,
    author: "Vercel",
    avatar: "https://github.com/vercel.png",
    fallback: "VC",
    views: 3456,
    likes: 234,
  },
  {
    id: 5,
    author: "React",
    avatar: "https://github.com/reactjs.png",
    fallback: "RT",
    views: 7890,
    likes: 567,
  },
  {
    id: 1,
    author: "Max Leiter",
    avatar: "https://github.com/maxleiter.png",
    fallback: "ML",
    views: 1234,
    likes: 123,
  },
  {
    id: 2,
    author: "Evil Rabbit",
    avatar: "https://github.com/evilrabbit.png",
    fallback: "ER",
    views: 5678,
    likes: 456,
  },
  {
    id: 3,
    author: "Shadcn",
    avatar: "https://github.com/shadcn.png",
    fallback: "SH",
    views: 9012,
    likes: 789,
  },
  {
    id: 4,
    author: "Vercel",
    avatar: "https://github.com/vercel.png",
    fallback: "VC",
    views: 3456,
    likes: 234,
  },
  {
    id: 5,
    author: "React",
    avatar: "https://github.com/reactjs.png",
    fallback: "RT",
    views: 7890,
    likes: 567,
  },
];

export const mentors = [
  {
    imgUrl: "",
    name: "박영미",
    career: "전문가(11년차)",
    job: "디자이너",
    role: "현 마이리얼트립 프로덕트 디자이너",
  },
  {
    imgUrl: "",
    name: "박보은",
    career: "시니어(7년차)",
    job: "디자이너",
    role: "현 마이리얼트립 프로덕트 디자이너",
  },
  {
    imgUrl: "",
    name: "윤지영",
    career: "전문가(18년차)",
    job: "마케터",
    role: "현 마이리얼트립 프로덕트 디자이너",
  },
  {
    imgUrl: "",
    name: "이동민",
    career: "시니어(11년차)",
    job: "마케터",
    role: "현 마이리얼트립 프로덕트 디자이너",
  },
  {
    imgUrl: "",
    name: "개발자 9Diin",
    career: "시니어(7년차)",
    job: "디자이너",
    role: "현 마이리얼트립 프로덕트 디자이너",
  },
  {
    imgUrl: "",
    name: "개발자 9Diin",
    career: "시니어(7년차)",
    job: "마케터",
    role: "현 마이리얼트립 프로덕트 디자이너",
  },
];
export const recruitments = [
  {
    imgUrl: "",
    profileImgUrl: "",
    title: "그래픽 디자이너 (3D) 채용",
    company: "토스플레이스",
  },
  {
    imgUrl: "",
    profileImgUrl: "",
    title: "광고 대행사 디자이너 채용",
    company: "브레이커스",
  },
  {
    imgUrl: "",
    profileImgUrl: "",
    title: "[미리캔버스] 그래픽 디자이너]",
    company: "미리디",
  },
  {
    imgUrl: "",
    profileImgUrl: "",
    title: "그래픽 디자이너 (3D) 채용",
    company: "토스플레이스",
  },
  {
    imgUrl: "",
    profileImgUrl: "",
    title: "광고 대행사 디자이너 채용",
    company: "브레이커스",
  },
  {
    imgUrl: "",
    profileImgUrl: "",
    title: "[미리캔버스] 그래픽 디자이너]",
    company: "미리디",
  },
];
